version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: teza-de-licenta:local
    depends_on:
      - redis
      - db

  web:
    container_name: tdl-web
    image: teza-de-licenta:local
    pull_policy: never
    command: ./main serve
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis:6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: teza-de-licenta
      DB_NAME: tdl
    ports:
      - "8080:8080"
    depends_on:
      - worker

  worker:
    container_name: tdl-worker
    image: teza-de-licenta:local
    pull_policy: never
    command: ./main worker
    env_file:
      - .env
    environment:
      REDIS_ADDR: redis:6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: teza-de-licenta
      DB_NAME: tdl
    depends_on:
      - app
      - redis
      - db

  redis:
    image: redis:latest
    container_name: tdl-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: tdl-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teza-de-licenta
      POSTGRES_DB: tdl
    ports:
      - "5432:5432"